# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='idd',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
